spring:
  profiles:
    # dev: 开发环境；pro 生产环境
    active: ${active:dev}

  # hibernate 数据库 验证级别
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${show-sql:false}
  # 配置数据源
  datasource:
    url: jdbc:mysql://${datasource.url:127.0.0.1}:${datasource.port:3306}/${datasource.dbname:bus_ticket}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username:root}
    password: ${datasource.password:}
  # 启用 flyway
  flyway:
    enabled: true
  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
server:
  # 配置端口
  port: ${port:8002}
  servlet:
    session:
      timeout: 60m

---
# 开发环境（使用本机mysql数据库的开发环境）
spring:
  profiles: dev